version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin_social 
      POSTGRES_PASSWORD: ADMAdm1234
      POSTGRES_DB: db_social_wires
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
  social_wires:
    env_file:
      ./.env
    depends_on:
      - db
    links:
      - db 
    build: 
      context: .
      dockerfile: Dockerfile
    image:  social_wires_app
    container_name: social_wires_app
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
